/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CampanhasRouteImport } from './routes/campanhas'
import { Route as CuponsRouteImport } from './routes/cupons'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as EstoqueRouteImport } from './routes/estoque'
import { Route as MetasRouteImport } from './routes/metas'
import { Route as ApiPublicCronMetaSyncRouteImport } from './routes/api/public/cron/meta-sync'
import { Route as ApiPublicEstoqueSyncRouteImport } from './routes/api/public/estoque/sync'
import { Route as ApiPublicShopifyWebhookRouteImport } from './routes/api/public/shopify/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CampanhasRoute = CampanhasRouteImport.update({
  id: '/campanhas',
  path: '/campanhas',
  getParentRoute: () => rootRouteImport,
} as any)
const CuponsRoute = CuponsRouteImport.update({
  id: '/cupons',
  path: '/cupons',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const EstoqueRoute = EstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => rootRouteImport,
} as any)
const MetasRoute = MetasRouteImport.update({
  id: '/metas',
  path: '/metas',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronMetaSyncRoute = ApiPublicCronMetaSyncRouteImport.update({
  id: '/api/public/cron/meta-sync',
  path: '/api/public/cron/meta-sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicEstoqueSyncRoute = ApiPublicEstoqueSyncRouteImport.update({
  id: '/api/public/estoque/sync',
  path: '/api/public/estoque/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicShopifyWebhookRoute = ApiPublicShopifyWebhookRouteImport.update({
  id: '/api/public/shopify/webhook',
  path: '/api/public/shopify/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/campanhas': typeof CampanhasRoute
  '/cupons': typeof CuponsRoute
  '/entrar': typeof EntrarRoute
  '/estoque': typeof EstoqueRoute
  '/metas': typeof MetasRoute
  '/api/public/cron/meta-sync': typeof ApiPublicCronMetaSyncRoute
  '/api/public/estoque/sync': typeof ApiPublicEstoqueSyncRoute
  '/api/public/shopify/webhook': typeof ApiPublicShopifyWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/campanhas': typeof CampanhasRoute
  '/cupons': typeof CuponsRoute
  '/entrar': typeof EntrarRoute
  '/estoque': typeof EstoqueRoute
  '/metas': typeof MetasRoute
  '/api/public/cron/meta-sync': typeof ApiPublicCronMetaSyncRoute
  '/api/public/estoque/sync': typeof ApiPublicEstoqueSyncRoute
  '/api/public/shopify/webhook': typeof ApiPublicShopifyWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/campanhas': typeof CampanhasRoute
  '/cupons': typeof CuponsRoute
  '/entrar': typeof EntrarRoute
  '/estoque': typeof EstoqueRoute
  '/metas': typeof MetasRoute
  '/api/public/cron/meta-sync': typeof ApiPublicCronMetaSyncRoute
  '/api/public/estoque/sync': typeof ApiPublicEstoqueSyncRoute
  '/api/public/shopify/webhook': typeof ApiPublicShopifyWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/campanhas'
    | '/cupons'
    | '/entrar'
    | '/estoque'
    | '/metas'
    | '/api/public/cron/meta-sync'
    | '/api/public/estoque/sync'
    | '/api/public/shopify/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/campanhas'
    | '/cupons'
    | '/entrar'
    | '/estoque'
    | '/metas'
    | '/api/public/cron/meta-sync'
    | '/api/public/estoque/sync'
    | '/api/public/shopify/webhook'
  id:
    | '__root__'
    | '/'
    | '/campanhas'
    | '/cupons'
    | '/entrar'
    | '/estoque'
    | '/metas'
    | '/api/public/cron/meta-sync'
    | '/api/public/estoque/sync'
    | '/api/public/shopify/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CampanhasRoute: typeof CampanhasRoute
  CuponsRoute: typeof CuponsRoute
  EntrarRoute: typeof EntrarRoute
  EstoqueRoute: typeof EstoqueRoute
  MetasRoute: typeof MetasRoute
  ApiPublicCronMetaSyncRoute: typeof ApiPublicCronMetaSyncRoute
  ApiPublicEstoqueSyncRoute: typeof ApiPublicEstoqueSyncRoute
  ApiPublicShopifyWebhookRoute: typeof ApiPublicShopifyWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campanhas': {
      id: '/campanhas'
      path: '/campanhas'
      fullPath: '/campanhas'
      preLoaderRoute: typeof CampanhasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cupons': {
      id: '/cupons'
      path: '/cupons'
      fullPath: '/cupons'
      preLoaderRoute: typeof CuponsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estoque': {
      id: '/estoque'
      path: '/estoque'
      fullPath: '/estoque'
      preLoaderRoute: typeof EstoqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metas': {
      id: '/metas'
      path: '/metas'
      fullPath: '/metas'
      preLoaderRoute: typeof MetasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/meta-sync': {
      id: '/api/public/cron/meta-sync'
      path: '/api/public/cron/meta-sync'
      fullPath: '/api/public/cron/meta-sync'
      preLoaderRoute: typeof ApiPublicCronMetaSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/estoque/sync': {
      id: '/api/public/estoque/sync'
      path: '/api/public/estoque/sync'
      fullPath: '/api/public/estoque/sync'
      preLoaderRoute: typeof ApiPublicEstoqueSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/shopify/webhook': {
      id: '/api/public/shopify/webhook'
      path: '/api/public/shopify/webhook'
      fullPath: '/api/public/shopify/webhook'
      preLoaderRoute: typeof ApiPublicShopifyWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CampanhasRoute: CampanhasRoute,
  CuponsRoute: CuponsRoute,
  EntrarRoute: EntrarRoute,
  EstoqueRoute: EstoqueRoute,
  MetasRoute: MetasRoute,
  ApiPublicCronMetaSyncRoute: ApiPublicCronMetaSyncRoute,
  ApiPublicEstoqueSyncRoute: ApiPublicEstoqueSyncRoute,
  ApiPublicShopifyWebhookRoute: ApiPublicShopifyWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
